version: "3.9"
services:
  nginx:
    build:
      dockerfile: ./Dockerfile
    ports:
      - "8080:80"
    environment:
      - NGINX_HOST=nonbleedingedge.com
      - NGINX_PORT=80
    networks:
      - nbe

networks:
  nbe:
    driver: bridge